<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WellnessCompanion</AssemblyName>
    <RootNamespace>WellnessCompanion</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.ico" />
    <EmbeddedResource Include="Assets\logo.ico" />
    <EmbeddedResource Include="Assets\haarcascade_frontalface_default.xml" />
  </ItemGroup>

</Project>
